// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3Tkllvx8r3eSMutU3qSY5BYPocnNGxy0',
    appId: '1:218704881410:android:4acab4c0237a9d4120441b',
    messagingSenderId: '218704881410',
    projectId: 'jlpt-practice-20a4e',
    storageBucket: 'jlpt-practice-20a4e.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAS5DWeMsnJ7ihsWDLSSnPxXU11Gn_DozE',
    appId: '1:218704881410:ios:21eac361f570ae5d20441b',
    messagingSenderId: '218704881410',
    projectId: 'jlpt-practice-20a4e',
    storageBucket: 'jlpt-practice-20a4e.firebasestorage.app',
    androidClientId: '218704881410-qbfibk4mq3ct1te7ujlu7jddh8po5tsk.apps.googleusercontent.com',
    iosClientId: '218704881410-cjrdtpl32hel789qqvt9p7b7929cm39p.apps.googleusercontent.com',
    iosBundleId: 'com.jlptpractice.jlptPractice',
  );
}
