import 'package:flutter/material.dart';

class AppStrings {
  const AppStrings(this.languageCode);

  final String languageCode;

  static const _en = <String, String>{
    'appName': 'Kotoba Flow',
    'continue': 'Continue',
    'getStarted': 'Start learning',
    'onboardingTitle': 'Build a Japanese habit',
    'onboardingBody': 'Short sessions, smart reviews, steady progress.',
    'chooseLevel': 'Choose your JLPT level',
    'dailyGoal': 'Daily word goal',
    'chooseStudyDay': 'Choose a study day',
    'day': 'Day',
    'days': 'days',
    'wordsPerDay': 'words per day',
    'recommended': 'Next',
    'language': 'Language',
    'languages': 'Languages',
    'levels': 'Levels',
    'beginner': 'For beginners',
    'elementary': 'Elementary',
    'intermediate': 'Intermediate',
    'upperIntermediate': 'Upper intermediate',
    'advanced': 'Advanced',
    'autoAudio': 'Automatic pronunciation',
    'swipeHint': 'Swipe left for the next word, right to go back.',
    'home': 'Home',
    'words': 'Words',
    'progress': 'Progress',
    'settings': 'Settings',
    'welcomeBack': 'Ready for today?',
    'dailyMomentum': 'Daily momentum',
    'wordsStudied': 'Words studied',
    'reviewsDue': 'Reviews due',
    'streak': 'day streak',
    'startStudy': 'Study new words',
    'studyGrammar': 'Study grammar',
    'grammarByRank': 'Browse every grammar point by JLPT rank',
    'grammar': 'Grammar',
    'searchGrammar': 'Search grammar, formation, or explanation',
    'noGrammarResults': 'No matching grammar points',
    'formation': 'Formation',
    'explanation': 'Explanation',
    'examples': 'Examples',
    'startReview': 'Review due cards',
    'startQuiz': 'Take a quick quiz',
    'recentActivity': 'Your progress',
    'learned': 'Learned',
    'learning': 'Learning',
    'search': 'Search Japanese, reading, or meaning',
    'all': 'All',
    'noResults': 'No matching vocabulary',
    'meaning': 'Meaning',
    'example': 'Example',
    'hideReading': 'Hide reading',
    'showReading': 'Show reading',
    'markReview': 'Add to review',
    'details': 'Word details',
    'question': 'Question',
    'quizInstruction': 'Choose the word that completes the sentence.',
    'correct': 'Correct',
    'incorrect': 'Not quite',
    'next': 'Next',
    'seeResults': 'See results',
    'quizComplete': 'Session complete',
    'accuracy': 'Accuracy',
    'correctAnswers': 'Correct answers',
    'duration': 'Study time',
    'retry': 'Try again',
    'backHome': 'Back to home',
    'reviewTitle': 'Due review',
    'tapReveal': 'Tap the card to reveal the answer',
    'again': 'Again',
    'hard': 'Hard',
    'good': 'Good',
    'easy': 'Easy',
    'queueComplete': 'You’re all caught up',
    'queueCompleteBody': 'No reviews are due. A few new words are ready.',
    'weeklyActivity': 'Weekly activity',
    'totalStudied': 'Total studied',
    'totalLearned': 'Total learned',
    'quizAccuracy': 'Quiz accuracy',
    'appearance': 'Appearance',
    'system': 'System',
    'light': 'Light',
    'dark': 'Dark',
    'showFurigana': 'Show furigana',
    'notifications': 'Daily reminder',
    'privacy': 'Privacy & consent',
    'attribution': 'Data attribution',
    'resetProgress': 'Reset learning progress',
    'resetConfirm': 'This removes study history on this device.',
    'cancel': 'Cancel',
    'reset': 'Reset',
    'anonymousNotice': 'Local-first anonymous account',
    'anonymousBody':
        'Clearing app data may remove access to study history until an account-linking option is available.',
    'privacyBody':
        'Only study settings and anonymous usage identifiers are used. Ad consent choices become available when ads are enabled.',
    'attributionBody':
        'Ranked vocabulary and grammar are imported from the MIT-licensed tristcoil/hanabira.org dataset. Vocabulary examples include generated content.',
    'offlineMode': 'Works offline',
    'adDevelopment': 'Ad space · development mode',
    'kanaChart': 'Hiragana & Katakana',
    'kanaChartSubtitle': 'Review the basic kana chart',
    'hiragana': 'Hiragana',
    'katakana': 'Katakana',
  };

  static const _ko = <String, String>{
    'appName': '코토바 플로우',
    'continue': '계속',
    'getStarted': '학습 시작',
    'onboardingTitle': '일본어 습관을 만들어 보세요',
    'onboardingBody': '짧은 학습, 스마트 복습, 꾸준한 성장.',
    'chooseLevel': 'JLPT 급수 선택',
    'dailyGoal': '하루 단어 목표',
    'chooseStudyDay': '학습할 날짜 선택',
    'day': 'Day',
    'days': '일',
    'wordsPerDay': '단어/일',
    'recommended': '다음',
    'language': '언어',
    'languages': '언어',
    'levels': '급수',
    'beginner': '입문',
    'elementary': '초급',
    'intermediate': '중급',
    'upperIntermediate': '중상급',
    'advanced': '고급',
    'autoAudio': '자동 발음 재생',
    'swipeHint': '왼쪽으로 넘기면 다음 단어, 오른쪽은 이전 단어예요.',
    'home': '홈',
    'words': '단어',
    'progress': '진행',
    'settings': '설정',
    'welcomeBack': '오늘도 시작해 볼까요?',
    'dailyMomentum': '오늘의 흐름',
    'wordsStudied': '학습한 단어',
    'reviewsDue': '복습할 단어',
    'streak': '일 연속',
    'startStudy': '새 단어 학습',
    'studyGrammar': '문법 학습',
    'grammarByRank': 'JLPT 급수별 전체 문법 보기',
    'grammar': '문법',
    'searchGrammar': '문법, 구성, 설명 검색',
    'noGrammarResults': '일치하는 문법 항목이 없습니다',
    'formation': '문형',
    'explanation': '설명',
    'examples': '예문',
    'startReview': '복습 시작',
    'startQuiz': '빠른 퀴즈',
    'recentActivity': '학습 현황',
    'learned': '완료',
    'learning': '학습 중',
    'search': '일본어, 읽기, 뜻 검색',
    'all': '전체',
    'noResults': '일치하는 단어가 없습니다',
    'meaning': '뜻',
    'example': '예문',
    'hideReading': '읽기 숨기기',
    'showReading': '읽기 보기',
    'markReview': '복습에 추가',
    'details': '단어 상세',
    'question': '문제',
    'quizInstruction': '문장을 완성하는 단어를 고르세요.',
    'correct': '정답이에요',
    'incorrect': '아쉬워요',
    'next': '다음',
    'seeResults': '결과 보기',
    'quizComplete': '학습 완료',
    'accuracy': '정확도',
    'correctAnswers': '정답',
    'duration': '학습 시간',
    'retry': '다시 하기',
    'backHome': '홈으로',
    'reviewTitle': '오늘의 복습',
    'tapReveal': '카드를 눌러 답을 확인하세요',
    'again': '다시',
    'hard': '어려움',
    'good': '좋음',
    'easy': '쉬움',
    'queueComplete': '오늘 복습을 마쳤어요',
    'queueCompleteBody': '예정된 복습이 없습니다. 새 단어를 학습해 보세요.',
    'weeklyActivity': '주간 학습',
    'totalStudied': '전체 학습',
    'totalLearned': '학습 완료',
    'quizAccuracy': '퀴즈 정확도',
    'appearance': '화면 모드',
    'system': '시스템',
    'light': '라이트',
    'dark': '다크',
    'showFurigana': '후리가나 표시',
    'notifications': '매일 알림',
    'privacy': '개인정보 및 동의',
    'attribution': '데이터 출처',
    'resetProgress': '학습 기록 초기화',
    'resetConfirm': '이 기기의 학습 기록이 삭제됩니다.',
    'cancel': '취소',
    'reset': '초기화',
    'anonymousNotice': '로컬 우선 익명 계정',
    'anonymousBody': '향후 계정 연결 기능이 제공되기 전에는 앱 데이터를 삭제하면 학습 기록에 접근하지 못할 수 있습니다.',
    'privacyBody': '학습 설정과 익명 사용 식별자만 사용합니다. 광고를 활성화하면 광고 동의 선택 항목이 제공됩니다.',
    'attributionBody':
        '급수별 단어와 문법은 MIT 라이선스의 tristcoil/hanabira.org 데이터셋에서 가져왔으며, 단어 예문에는 생성된 콘텐츠가 포함됩니다.',
    'offlineMode': '오프라인 사용 가능',
    'adDevelopment': '광고 영역 · 개발 모드',
    'kanaChart': '히라가나 & 가타카나',
    'kanaChartSubtitle': '기본 가나표를 확인하세요',
    'hiragana': '히라가나',
    'katakana': '가타카나',
  };

  String call(String key) =>
      (languageCode == 'ko' ? _ko : _en)[key] ?? _en[key] ?? key;
}

extension AppStringsContext on BuildContext {
  AppStrings get strings =>
      AppStrings(Localizations.localeOf(this).languageCode);
}
