import 'package:flutter/material.dart';

class AppStrings {
  const AppStrings(this.languageCode);

  final String languageCode;

  static const _en = <String, String>{
    'appName': 'JLPT study',
    'continue': 'Continue',
    'getStarted': 'Start learning',
    'onboardingTitle': 'Build a Japanese habit',
    'onboardingBody': 'Short sessions, smart reviews, steady progress.',
    'chooseLevel': 'Choose your JLPT level',
    'chooseStudyDay': 'Choose a study day',
    'day': 'Day',
    'days': 'days',
    'wordsPerDay': 'words per day',
    'recommended': 'Next',
    'language': 'Language',
    'languages': 'Languages',
    'learningLanguage': 'Learning language',
    'learningSettings': 'Learning settings',
    'eyeComfort': 'Eye comfort mode',
    'eyeComfortStrength': 'Warmth',
    'levels': 'Levels',
    'beginner': 'For beginners',
    'elementary': 'Elementary',
    'intermediate': 'Intermediate',
    'upperIntermediate': 'Upper intermediate',
    'advanced': 'Advanced',
    'autoAudio': 'Automatic pronunciation',
    'swipeHint': 'Swipe left for the next word, right to go back.',
    'home': 'Home',
    'words': 'Words',
    'progress': 'Progress',
    'settings': 'Settings',
    'me': 'Me',
    'welcomeBack': 'Ready for today?',
    'dailyMomentum': 'Daily momentum',
    'wordsStudied': 'Words studied',
    'streak': 'day streak',
    'study': 'Study',
    'chooseStudyType': 'Choose what to study',
    'startStudy': 'Study new words',
    'studyVocabularySubtitle': 'Learn today’s new words',
    'resumeLearning': 'Resume learning',
    'resumeConfirmTitle': 'Continue your recent session?',
    'resumeConfirmBody': 'Resume from the word where you stopped?',
    'chooseAnotherDay': 'Choose another day',
    'finishSession': 'Finish this session',
    'finishSessionConfirm': 'Finish this study session?',
    'finishSessionConfirmBody':
        'Your saved position for this session will be cleared.',
    'finish': 'Finish',
    'studyComplete': 'Great work!',
    'studyCompleteBody': 'You’ve gone through today’s words.',
    'studyGrammar': 'Study grammar',
    'grammarByRank': 'Browse every grammar point by JLPT rank',
    'grammar': 'Grammar',
    'searchGrammar': 'Search grammar, formation, or explanation',
    'noGrammarResults': 'No matching grammar points',
    'formation': 'Formation',
    'explanation': 'Explanation',
    'examples': 'Examples',
    'part': 'Part',
    'practice': 'Practice',
    'rank': 'Rank',
    'combinedQuestionPool': 'Combined question pool',
    'ranks': 'Ranks',
    'of': 'of',
    'practised': 'practised',
    'practiceWithAi': 'Practise with AI',
    'startPartCheckpoint': 'Start part checkpoint',
    'continueWithAiTutor': 'Continue with AI tutor',
    'checkUnderstanding': 'Check my understanding',
    'chooseGrammarExample': 'Which sentence uses this grammar point?',
    'writeOwnSentence': 'Write your own Japanese sentence',
    'useTargetGrammar': 'Use the target grammar naturally in one sentence.',
    'checkWithAi': 'Check with AI',
    'enterSentence': 'Enter a sentence first.',
    'aiFeedbackError':
        'AI feedback is unavailable. Check your connection and try again.',
    'lessonComplete': 'Grammar lesson complete',
    'aiFeedback': 'Tutor feedback',
    'practiceAgain': 'Practise again',
    'understand': 'Understand',
    'apply': 'Apply',
    'produce': 'Produce',
    'result': 'Result',
    'checkpointComplete': 'Part checkpoint complete',
    'strong': 'Strong',
    'reviewNext': 'Review next',
    'practiceWeakPoints': 'Practise weak points',
    'answer': 'Answer',
    'meaningNotRecognized': 'Meaning not recognized in the part checkpoint.',
    'none': 'None yet',
    'newItem': 'New',
    'familiar': 'Familiar',
    'mastered': 'Mastered',
    'startQuiz': 'Take a quick quiz',
    'recentStudy': 'Recent study',
    'offlineAi': 'Offline grammar AI',
    'offlineManage': 'Download, test, or remove the model',
    'offlineIntro': 'Practise grammar on your device',
    'offlinePrivacy':
        'Download a model once to get grammar feedback offline. Your sentences are processed on this device. Other AI features may still use online services.',
    'offlineRam': 'Device memory',
    'offlineStorage': 'Free storage',
    'offlineSmallModel': 'Smaller download · lighter memory use',
    'offlineLargeModel': 'Larger model · needs more memory',
    'offlineInstalled': 'Downloaded',
    'offlinePartial': 'Saved download',
    'offlineWifiOnly': 'Download on Wi-Fi only',
    'offlineQualityNote':
        'Experimental feedback may be inaccurate, especially for Japanese and Korean. Compare it with the lesson explanation. Keep this screen open during download. Built with Llama.',
    'offlineChecking': 'Checking your device…',
    'offlineDownloading': 'Downloading model…',
    'offlineVerifying': 'Verifying model…',
    'offlineLoading': 'Testing the model on your device…',
    'offlineEvaluating': 'Generating offline feedback…',
    'offlinePause': 'Pause download',
    'offlineDownload': 'Download model',
    'offlineResumeDownload': 'Resume download',
    'offlineTestModel': 'Test model',
    'offlineReady': 'Model loaded successfully. Offline grammar AI is ready.',
    'offlineDelete': 'Delete model',
    'offlineDeleteBody':
        'Remove this model and any partial download? Your learning progress stays saved. You can download the model again.',
    'offlineLicense': 'Llama license and attribution',
    'offlineUnsupported':
        'This model is not supported on this device. Try the smaller model. Regular lessons are still available.',
    'offlineTooHot':
        'Your device is too warm. Let it cool before using offline AI.',
    'offlineLowMemory':
        'Not enough memory is available right now. Close other apps or choose the smaller model in Settings → Offline grammar AI.',
    'offlineLowStorage':
        'Not enough free storage for this download. Free some space and try again.',
    'offlineWifiRequired':
        'Connect to Wi-Fi, or turn off Wi-Fi-only downloads to use mobile data.',
    'offlinePaused':
        'Paused. Return here to resume the download or retry offline AI.',
    'offlineBusy': 'Offline AI is busy. Please wait for the current operation.',
    'offlineDownloadError':
        'Download interrupted. Check your connection and resume; your downloaded data is saved.',
    'offlineIntegrityError':
        'The model failed verification. Download it again before using offline AI.',
    'offlineStorageError': 'The model could not be removed. Try again.',
    'offlineInferenceError':
        'The local model could not finish. Try again or choose the smaller model in Settings → Offline grammar AI.',
    'offlineSetupRequired':
        'Download a model in Settings → Offline grammar AI first.',
    'offlineSentenceLimit':
        'Enter a Japanese sentence of up to 300 characters.',
    'offlineQuestionLimit': 'Enter a question of up to 300 characters.',
    'offlineInvalidResponse':
        'The model could not produce usable feedback. Try again. Your answer has not been graded.',
    'askAboutThisGrammar': 'Ask about this grammar point',
    'askAboutThisGrammarHint': 'e.g. When can I use this instead of...?',
    'askSuggestionWhenToUse': 'When do I use this?',
    'askSuggestionMoreExamples': 'Give me another example',
    'askSuggestionDifference': 'How is this different from similar grammar?',
    'previousStudy': 'Previous',
    'continueLesson': 'Continue your lesson',
    'wordProgress': '{current} of {total} words',
    'recentActivity': 'Your progress',
    'learned': 'Learned',
    'learning': 'Learning',
    'search': 'Search Japanese, reading, or meaning',
    'all': 'All',
    'noResults': 'No matching vocabulary',
    'meaning': 'Meaning',
    'hideReading': 'Hide reading',
    'showReading': 'Show reading',
    'details': 'Word details',
    'question': 'Question',
    'quizInstruction': 'Choose the word that completes the sentence.',
    'correct': 'Correct',
    'incorrect': 'Not quite',
    'next': 'Next',
    'seeResults': 'See results',
    'quizComplete': 'Session complete',
    'accuracy': 'Accuracy',
    'correctAnswers': 'Correct answers',
    'duration': 'Study time',
    'retry': 'Try again',
    'backHome': 'Back to home',
    'weeklyActivity': 'Weekly activity',
    'totalStudied': 'Total studied',
    'totalLearned': 'Total learned',
    'quizAccuracy': 'Quiz accuracy',
    'appearance': 'Appearance',
    'system': 'System',
    'light': 'Light',
    'dark': 'Dark',
    'showFurigana': 'Show furigana',
    'notifications': 'Daily reminder',
    'reminderTime': 'Reminder time',
    'notificationPermissionDenied':
        'Notifications are disabled. Allow them in system settings to use reminders.',
    'privacy': 'Privacy & consent',
    'attribution': 'Data attribution',
    'resetProgress': 'Reset learning progress',
    'resetConfirm': 'This removes study history on this device.',
    'cancel': 'Cancel',
    'reset': 'Reset',
    'account': 'Account',
    'protectProgress': 'Protect your progress',
    'protectProgressTitle': 'Sign in to protect your progress',
    'protectProgressBody':
        'Your current study history will be linked to your account and restored after reinstalling the app.',
    'welcomeSignInTitle': 'Sign in to get started',
    'welcomeSignInBody':
        'Create an account or sign in so your progress saves and syncs across every device.',
    'createAccountTitle': 'Create your account',
    'signInWithGoogle': 'Sign in with Google',
    'signUpWithGoogle': 'Sign up with Google',
    'continueWithApple': 'Continue with Apple',
    'orContinueWith': 'or continue with',
    'email': 'Email',
    'password': 'Password',
    'confirmPassword': 'Confirm password',
    'signIn': 'Sign in',
    'signUp': 'Sign up',
    'signOut': 'Sign out',
    'forgotPassword': 'Forgot password?',
    'needAccount': 'New here? Create an account',
    'alreadyHaveAccount': 'Already have an account? Sign in',
    'enterValidEmail': 'Enter a valid email address.',
    'passwordRequirement': 'Your password does not meet the requirements.',
    'passwordConstraintLength': 'At least 8 characters',
    'passwordConstraintUppercase': 'At least one uppercase letter',
    'passwordConstraintLowercase': 'At least one lowercase letter',
    'passwordConstraintNumber': 'At least one number',
    'passwordsDoNotMatch': 'Passwords do not match.',
    'emailAlreadyInUse': 'That email already has an account. Sign in instead.',
    'weakPassword': 'Choose a stronger password.',
    'invalidCredentials': 'The email or password is incorrect.',
    'tooManyRequests': 'Too many attempts. Please wait and try again.',
    'accountError': 'Account access failed. Please try again.',
    'resetEmailSent': 'Password reset email sent.',
    'progressProtected': 'Your study progress is now protected.',
    'syncActive': 'Cloud sync is active',
    'syncActiveBody': 'Study progress is saved to your account automatically.',
    'emailNotVerified': 'Email address not verified',
    'resend': 'Resend',
    'verificationSent': 'Verification email sent.',
    'signOutConfirm':
        'Your cloud data will stay in your account. Local account data will be removed from this device.',
    'deleteAccount': 'Delete account',
    'deleteAccountConfirm':
        'This permanently deletes your account and all synchronized study data. This cannot be undone.',
    'optOut': 'Opt out',
    'profile': 'Profile',
    'authMethod': 'Sign-in method',
    'anonymousBody':
        'Sign in to restore your study history after reinstalling or changing devices.',
    'privacyBody':
        'Only study settings and anonymous usage identifiers are used. Ad consent choices become available when ads are enabled.',
    'attributionBody':
        'Ranked vocabulary and grammar are imported from the MIT-licensed tristcoil/hanabira.org dataset. Vocabulary examples include generated content.',
    'offlineMode': 'Works offline',
    'networkDisconnectedTitle': 'No internet connection',
    'networkDisconnectedBody':
        'Check your Wi-Fi or mobile data connection and try again.',
    'networkRetry': 'Try again',
    'kanaChart': 'Hiragana & Katakana',
    'kanaChartTile': 'Hiragana\nKatakana',
    'kanaChartSubtitle': 'Review the basic kana chart',
    'hiragana': 'Hiragana',
    'katakana': 'Katakana',
    'kanaGroupVowels': 'Vowels',
    'kanaGroupConsonants': 'Consonants (CV)',
    'kanaGroupGlides': 'Semivowels & Glides',
    'kanaGroupVoiced': 'Voiced & Semi-voiced (Dakuon / Handakuon)',
    'kanaGroupYoon': 'Yōon — Contracted Sounds (CyV)',
    'kanaGroupSpecial': 'Special Moraic Elements',
    'kanaGroupSpecialNote':
        'ん adds a nasal mora on its own. っ doubles the consonant that follows it. ー lengthens the preceding vowel (mainly in katakana).',
    'totalXp': 'Total XP',
    'earnBonusXp': 'Earn bonus XP',
    'xpEarned': 'XP earned',
    'n5Test': 'Test',
    'sectionVocabulary': 'Vocabulary',
    'grammarQuizInstruction':
        'Choose the meaning that matches the grammar point.',
    'mockTestComplete': 'Test complete',
    'sectionResults': 'Section results',
    'lowVolumeTitle': 'Volume is too low',
    'lowVolumeBody':
        'Turn up your device volume or unmute it to hear the pronunciation.',
    'sectionReading': 'Reading',
    'practiceTest': 'Practice',
    'readingQuizInstruction': 'Read the passage, then choose the best answer.',
    'showExplanation': 'Show explanation',
    'hideExplanation': 'Hide explanation',
    'chooseQuestionType': 'Choose a question type',
    'languageKnowledgeVocabulary':
        'Language Knowledge · Characters & Vocabulary',
    'languageKnowledgeGrammar': 'Language Knowledge · Grammar',
    'readingComprehension': 'Reading Comprehension',
    'listeningComprehension': 'Listening Comprehension',
    'sectionListening': 'Listening',
    'listeningQuizInstruction':
        'Listen to the conversation, then choose the best answer.',
    'playAudio': 'Play audio',
    'askAiTutor': 'Ask AI Tutor',
    'askingAiTutor': 'Asking AI Tutor…',
    'aiTutor': 'AI Tutor',
    'aiGeneratedNotice': 'AI-generated guidance may contain mistakes.',
    'whyCorrect': 'Why this answer is correct',
    'whyWrong': 'Why your answer was incorrect',
    'keyEvidence': 'Key evidence',
    'learningPoints': 'Key learning points',
    'explainChoices': 'Explain the choices',
    'showEvidence': 'Show the key evidence',
    'giveExample': 'Give me a similar example',
    'aiTutorUnavailable':
        'AI Tutor is unavailable right now. The stored explanation is still available.',
    'aiTutorBusy':
        'AI Tutor has reached its temporary request limit. Wait about a minute, then try again. The stored explanation is still available.',
    'tryAgain': 'Try again',
    'wasHelpful': 'Was this helpful?',
    'thanksFeedback': 'Thanks for your feedback.',
    'askFollowUp': 'Ask a follow-up question',
    'typeYourQuestion': 'Type your question…',
    'sendMessage': 'Send',
    'temporaryChatNotice': 'This conversation is deleted when you close it.',
    'aiReplyError': 'The tutor could not reply. Please try again.',
    'conversationLimit': 'You have reached the limit for this conversation.',
    'unlockDaysTitle': 'Unlock Day {day}',
    'unlockDaysBody': 'Watch a short ad to study Day {day}.',
    'finishPreviousDaysTitle': 'Finish earlier days first',
    'finishPreviousDaysBody':
        'Complete Days 1–{day} before starting this study day.',
    'watchAd': 'Watch ad',
    'hideWord': 'Hide word',
    'showWord': 'Show word',
    'hideMeanings': 'Hide meanings',
    'showMeanings': 'Show meanings',
    'covered': 'Hidden',
    'on': 'On',
    'off': 'Off',
    'groupLanguage': 'Language',
    'groupReadingAudio': 'Reading & pronunciation',
    'groupReview': 'Review',
    'groupDisplay': 'Display',
    'autoReview': 'Auto review',
    'autoReviewHint':
        'Each card reveals its word, meanings and reading one at a time in the order you choose, then moves to the next card by itself. It runs on days you have already finished.',
    'autoReviewEnable': 'Use auto review',
    'autoReviewOrder': 'Reveal order',
    'autoReviewSpeed': 'Time per step',
    'autoReviewSecondsFormat': '{n} sec',
    'elementWord': 'Word',
    'elementMeanings': 'Meanings',
    'elementReading': 'Reading',
    'pauseAutoReview': 'Pause',
    'resumeAutoReview': 'Resume',
    'recallCover': 'Hide and recall',
    'recallCoverHint':
        'Cover words and meanings with tape, then say them from memory. The buttons at the bottom of the study screen turn covers on and off.',
    'coverWordBody':
        'Covers the word, including where it appears in the example sentence.',
    'coverMeaningsTitle': 'Meanings',
    'coverMeaningsBody': 'Choose what the meanings cover hides.',
    'coverMeaningAndTranslation': 'Meanings and translations',
    'coverMeaningAndTranslationBody':
        'Covers the meaning and the example translation.',
    'coverMeaningOnly': 'Meanings only',
    'coverMeaningOnlyBody':
        'Covers the meaning, and its wording inside the example translation.',
    'coverTranslationOnly': 'Translations only',
    'coverTranslationOnlyBody': 'Covers only the example translation.',
    'ttsVolume': 'Pronunciation volume',
    'ttsVolumeHint':
        'Choose where the volume of spoken pronunciation comes from.',
    'volumeSystem': 'System volume',
    'volumeSystemBody':
        'Follows your device’s media volume. Change it with the volume buttons.',
    'volumeSlider': 'Custom level',
    'volumeSliderBody':
        'Plays at the level below whatever the device volume is set to, then puts the device volume back.',
    'volumeCurrentSystem': 'Current system volume',
    'volumeLevel': 'Volume',
    'eyeComfortSubtitle': 'Warm tint while you study',
  };

  static const _ko = <String, String>{
    'appName': 'JLPT 스터디',
    'continue': '계속',
    'getStarted': '학습 시작',
    'onboardingTitle': '일본어 습관을 만들어 보세요',
    'onboardingBody': '짧은 학습, 스마트 복습, 꾸준한 성장.',
    'chooseLevel': 'JLPT 급수 선택',
    'chooseStudyDay': '학습할 날짜 선택',
    'day': 'Day',
    'days': '일',
    'wordsPerDay': '단어/일',
    'recommended': '다음',
    'language': '언어',
    'languages': '언어',
    'learningLanguage': '학습 언어',
    'learningSettings': '학습 설정',
    'eyeComfort': '눈 보호 모드',
    'eyeComfortStrength': '색온도 강도',
    'levels': '급수',
    'beginner': '입문',
    'elementary': '초급',
    'intermediate': '중급',
    'upperIntermediate': '중상급',
    'advanced': '고급',
    'autoAudio': '자동 발음 재생',
    'swipeHint': '왼쪽으로 넘기면 다음 단어, 오른쪽은 이전 단어예요.',
    'home': '홈',
    'words': '단어',
    'progress': '진행',
    'settings': '설정',
    'me': '내 정보',
    'welcomeBack': '오늘도 시작해 볼까요?',
    'dailyMomentum': '오늘의 흐름',
    'wordsStudied': '학습한 단어',
    'streak': '일 연속',
    'study': '학습',
    'chooseStudyType': '무엇을 학습할까요?',
    'startStudy': '새 단어 학습',
    'studyVocabularySubtitle': '오늘의 새 단어 학습하기',
    'resumeLearning': '이어서 학습',
    'resumeConfirmTitle': '최근 학습을 이어갈까요?',
    'resumeConfirmBody': '마지막으로 보던 단어부터 이어서 학습할까요?',
    'chooseAnotherDay': '다른 날짜 선택',
    'finishSession': '이번 학습 마치기',
    'finishSessionConfirm': '이번 학습을 마칠까요?',
    'finishSessionConfirmBody': '저장된 학습 위치가 삭제됩니다.',
    'finish': '마치기',
    'studyComplete': '수고하셨어요!',
    'studyCompleteBody': '오늘의 단어를 모두 학습했어요.',
    'studyGrammar': '문법 학습',
    'grammarByRank': 'JLPT 급수별 전체 문법 보기',
    'grammar': '문법',
    'searchGrammar': '문법, 구성, 설명 검색',
    'noGrammarResults': '일치하는 문법 항목이 없습니다',
    'formation': '문형',
    'explanation': '설명',
    'examples': '예문',
    'part': '파트',
    'practice': '연습',
    'rank': '랭크',
    'combinedQuestionPool': '통합 문제 세트',
    'ranks': '순위',
    'of': '/',
    'practised': '개 연습',
    'practiceWithAi': 'AI로 연습하기',
    'startPartCheckpoint': '파트 진단 시작',
    'continueWithAiTutor': 'AI 튜터로 계속하기',
    'checkUnderstanding': '이해도 확인하기',
    'chooseGrammarExample': '이 문법을 사용한 문장은 무엇인가요?',
    'writeOwnSentence': '직접 일본어 문장을 써 보세요',
    'useTargetGrammar': '목표 문법을 자연스럽게 사용해 한 문장을 만드세요.',
    'checkWithAi': 'AI로 확인',
    'enterSentence': '먼저 문장을 입력해 주세요.',
    'aiFeedbackError': 'AI 피드백을 사용할 수 없습니다. 연결을 확인하고 다시 시도해 주세요.',
    'lessonComplete': '문법 학습 완료',
    'aiFeedback': '튜터 피드백',
    'practiceAgain': '다시 연습',
    'understand': '이해',
    'apply': '적용',
    'produce': '문장 만들기',
    'result': '결과',
    'checkpointComplete': '파트 진단 완료',
    'strong': '잘 아는 문법',
    'reviewNext': '다음 복습',
    'practiceWeakPoints': '약한 문법 연습',
    'answer': '정답',
    'meaningNotRecognized': '파트 진단에서 뜻을 구별하지 못했습니다.',
    'none': '아직 없음',
    'newItem': '새 문법',
    'familiar': '익숙함',
    'mastered': '완료',
    'startQuiz': '빠른 퀴즈',
    'recentStudy': '최근 학습',
    'offlineAi': '오프라인 문법 AI',
    'offlineManage': '모델 다운로드, 테스트 및 삭제',
    'offlineIntro': '내 기기에서 문법 연습하기',
    'offlinePrivacy':
        '모델을 한 번 다운로드하면 인터넷 없이 문법 피드백을 받을 수 있어요. 작성한 문장은 이 기기에서 처리됩니다. 다른 AI 기능은 온라인 서비스를 사용할 수 있어요.',
    'offlineRam': '기기 메모리',
    'offlineStorage': '여유 저장 공간',
    'offlineSmallModel': '작은 다운로드 · 적은 메모리 사용',
    'offlineLargeModel': '더 큰 모델 · 더 많은 메모리 필요',
    'offlineInstalled': '다운로드됨',
    'offlinePartial': '저장된 다운로드',
    'offlineWifiOnly': 'Wi-Fi에서만 다운로드',
    'offlineQualityNote':
        '실험적 기능으로 일본어·한국어 피드백이 부정확할 수 있어요. 학습 해설과 함께 확인해 주세요. 다운로드 중에는 이 화면을 열어 두세요. Built with Llama.',
    'offlineChecking': '기기를 확인하는 중…',
    'offlineDownloading': '모델 다운로드 중…',
    'offlineVerifying': '모델 검증 중…',
    'offlineLoading': '기기에서 모델을 테스트하는 중…',
    'offlineEvaluating': '오프라인 피드백 생성 중…',
    'offlinePause': '다운로드 일시정지',
    'offlineDownload': '모델 다운로드',
    'offlineResumeDownload': '다운로드 이어받기',
    'offlineTestModel': '모델 테스트',
    'offlineReady': '모델을 불러왔어요. 오프라인 문법 AI를 사용할 수 있습니다.',
    'offlineDelete': '모델 삭제',
    'offlineDeleteBody': '모델과 미완료 다운로드를 삭제할까요? 학습 기록은 유지되며 모델은 다시 다운로드할 수 있어요.',
    'offlineLicense': 'Llama 라이선스 및 출처',
    'offlineUnsupported':
        '이 기기에서는 이 모델을 지원하지 않아요. 더 작은 모델을 선택해 주세요. 일반 학습은 계속 이용할 수 있어요.',
    'offlineTooHot': '기기가 뜨거워요. 온도가 내려간 후 다시 시도해 주세요.',
    'offlineLowMemory':
        '현재 사용 가능한 메모리가 부족해요. 다른 앱을 닫거나 설정 → 오프라인 문법 AI에서 작은 모델을 선택해 주세요.',
    'offlineLowStorage': '다운로드에 필요한 저장 공간이 부족해요. 공간을 확보한 후 다시 시도해 주세요.',
    'offlineWifiRequired': 'Wi-Fi에 연결하거나 Wi-Fi 전용 설정을 꺼서 모바일 데이터를 사용해 주세요.',
    'offlinePaused': '일시정지했어요. 여기에서 다운로드를 이어받거나 오프라인 AI를 다시 시도할 수 있어요.',
    'offlineBusy': '오프라인 AI가 작업 중이에요. 잠시 기다려 주세요.',
    'offlineDownloadError':
        '다운로드가 중단됐어요. 연결을 확인하고 이어받기를 눌러 주세요. 받은 데이터는 저장되어 있어요.',
    'offlineIntegrityError': '모델 검증에 실패했어요. 모델을 다시 다운로드해 주세요.',
    'offlineStorageError': '모델을 삭제하지 못했어요. 다시 시도해 주세요.',
    'offlineInferenceError':
        '모델 실행에 실패했어요. 다시 시도하거나 설정 → 오프라인 문법 AI에서 작은 모델을 선택해 주세요.',
    'offlineSetupRequired': '먼저 설정 → 오프라인 문법 AI에서 모델을 다운로드해 주세요.',
    'offlineSentenceLimit': '300자 이내의 일본어 문장을 입력해 주세요.',
    'offlineQuestionLimit': '300자 이내의 질문을 입력해 주세요.',
    'offlineInvalidResponse':
        '모델이 올바른 형식의 피드백을 생성하지 못했어요. 다시 시도해 주세요. 답변은 채점되지 않았어요.',
    'askAboutThisGrammar': '이 문법에 대해 질문하기',
    'askAboutThisGrammarHint': '예: 이것과 비슷한 표현은 언제 쓰나요?',
    'askSuggestionWhenToUse': '언제 사용하나요?',
    'askSuggestionMoreExamples': '다른 예문을 보여주세요',
    'askSuggestionDifference': '비슷한 문법과 어떻게 다른가요?',
    'previousStudy': '이전 학습',
    'continueLesson': '학습 이어가기',
    'wordProgress': '{total}개 중 {current}번째 단어',
    'recentActivity': '학습 현황',
    'learned': '완료',
    'learning': '학습 중',
    'search': '일본어, 읽기, 뜻 검색',
    'all': '전체',
    'noResults': '일치하는 단어가 없습니다',
    'meaning': '뜻',
    'hideReading': '읽기 숨기기',
    'showReading': '읽기 보기',
    'details': '단어 상세',
    'question': '문제',
    'quizInstruction': '문장을 완성하는 단어를 고르세요.',
    'correct': '정답이에요',
    'incorrect': '아쉬워요',
    'next': '다음',
    'seeResults': '결과 보기',
    'quizComplete': '학습 완료',
    'accuracy': '정확도',
    'correctAnswers': '정답',
    'duration': '학습 시간',
    'retry': '다시 하기',
    'backHome': '홈으로',
    'weeklyActivity': '주간 학습',
    'totalStudied': '전체 학습',
    'totalLearned': '학습 완료',
    'quizAccuracy': '퀴즈 정확도',
    'appearance': '화면 모드',
    'system': '시스템',
    'light': '라이트',
    'dark': '다크',
    'showFurigana': '후리가나 표시',
    'notifications': '매일 알림',
    'reminderTime': '알림 시간',
    'notificationPermissionDenied': '알림이 허용되지 않았습니다. 기기 설정에서 알림을 허용해 주세요.',
    'privacy': '개인정보 및 동의',
    'attribution': '데이터 출처',
    'resetProgress': '학습 기록 초기화',
    'resetConfirm': '이 기기의 학습 기록이 삭제됩니다.',
    'cancel': '취소',
    'reset': '초기화',
    'account': '계정',
    'protectProgress': '학습 기록 보호하기',
    'protectProgressTitle': '로그인하여 학습 기록을 보호하세요',
    'protectProgressBody': '현재 학습 기록이 계정에 연결되어 앱을 다시 설치해도 복원됩니다.',
    'welcomeSignInTitle': '로그인하고 시작하기',
    'welcomeSignInBody': '계정을 만들거나 로그인하면 학습 기록이 저장되고 모든 기기에서 동기화됩니다.',
    'createAccountTitle': '계정 만들기',
    'signInWithGoogle': 'Google로 로그인',
    'signUpWithGoogle': 'Google로 가입하기',
    'continueWithApple': 'Apple로 계속',
    'orContinueWith': '또는 다음으로 계속',
    'email': '이메일',
    'password': '비밀번호',
    'confirmPassword': '비밀번호 확인',
    'signIn': '로그인',
    'signUp': '가입하기',
    'signOut': '로그아웃',
    'forgotPassword': '비밀번호를 잊으셨나요?',
    'needAccount': '처음이신가요? 계정 만들기',
    'alreadyHaveAccount': '계정이 있으신가요? 로그인',
    'enterValidEmail': '올바른 이메일 주소를 입력해 주세요.',
    'passwordRequirement': '비밀번호가 요구 조건을 충족하지 않습니다.',
    'passwordConstraintLength': '8자 이상',
    'passwordConstraintUppercase': '대문자 1개 이상',
    'passwordConstraintLowercase': '소문자 1개 이상',
    'passwordConstraintNumber': '숫자 1개 이상',
    'passwordsDoNotMatch': '비밀번호가 일치하지 않습니다.',
    'emailAlreadyInUse': '이미 가입된 이메일입니다. 로그인해 주세요.',
    'weakPassword': '더 안전한 비밀번호를 사용해 주세요.',
    'invalidCredentials': '이메일 또는 비밀번호가 올바르지 않습니다.',
    'tooManyRequests': '시도가 너무 많습니다. 잠시 후 다시 시도해 주세요.',
    'accountError': '계정에 연결하지 못했습니다. 다시 시도해 주세요.',
    'resetEmailSent': '비밀번호 재설정 이메일을 보냈습니다.',
    'progressProtected': '학습 기록이 계정에 안전하게 연결되었습니다.',
    'syncActive': '클라우드 동기화 사용 중',
    'syncActiveBody': '학습 기록이 계정에 자동으로 저장됩니다.',
    'emailNotVerified': '이메일 주소가 인증되지 않았습니다',
    'resend': '다시 보내기',
    'verificationSent': '인증 이메일을 보냈습니다.',
    'signOutConfirm': '클라우드 기록은 계정에 유지되며 이 기기의 계정 데이터는 삭제됩니다.',
    'deleteAccount': '계정 삭제',
    'deleteAccountConfirm': '계정과 동기화된 모든 학습 기록이 영구 삭제됩니다. 되돌릴 수 없습니다.',
    'optOut': '탈퇴하기',
    'profile': '프로필',
    'authMethod': '로그인 방법',
    'anonymousBody': '로그인하면 앱 재설치 또는 기기 변경 후에도 학습 기록을 복원할 수 있습니다.',
    'privacyBody': '학습 설정과 익명 사용 식별자만 사용합니다. 광고를 활성화하면 광고 동의 선택 항목이 제공됩니다.',
    'attributionBody':
        '급수별 단어와 문법은 MIT 라이선스의 tristcoil/hanabira.org 데이터셋에서 가져왔으며, 단어 예문에는 생성된 콘텐츠가 포함됩니다.',
    'offlineMode': '오프라인 사용 가능',
    'networkDisconnectedTitle': '인터넷에 연결되어 있지 않아요',
    'networkDisconnectedBody': 'Wi-Fi 또는 모바일 데이터 연결을 확인한 후 다시 시도해 주세요.',
    'networkRetry': '다시 시도',
    'kanaChart': '히라가나 & 가타카나',
    'kanaChartTile': '히라가나\n가타카나',
    'kanaChartSubtitle': '기본 가나표를 확인하세요',
    'hiragana': '히라가나',
    'katakana': '가타카나',
    'kanaGroupVowels': '모음',
    'kanaGroupConsonants': '자음 (CV)',
    'kanaGroupGlides': '반모음 · 활음',
    'kanaGroupVoiced': '탁음 · 반탁음',
    'kanaGroupYoon': '요음 — 축약음 (CyV)',
    'kanaGroupSpecial': '특수 모라 요소',
    'kanaGroupSpecialNote':
        'ん은 그 자체로 비음 모라를 추가합니다. っ은 뒤따르는 자음을 촉음화(중복)합니다. ー는 앞의 모음을 길게 늘립니다(주로 가타카나에서 사용).',
    'totalXp': '총 XP',
    'earnBonusXp': '보너스 XP 받기',
    'xpEarned': 'XP 획득',
    'n5Test': '테스트',
    'sectionVocabulary': '어휘',
    'grammarQuizInstruction': '문법 항목에 맞는 뜻을 고르세요.',
    'mockTestComplete': '테스트 완료',
    'sectionResults': '섹션별 결과',
    'lowVolumeTitle': '볼륨이 너무 낮습니다',
    'lowVolumeBody': '발음을 들으려면 기기 볼륨을 높이거나 음소거를 해제하세요.',
    'sectionReading': '독해',
    'practiceTest': '연습',
    'readingQuizInstruction': '지문을 읽고 가장 알맞은 답을 고르세요.',
    'showExplanation': '해설 보기',
    'hideExplanation': '해설 숨기기',
    'chooseQuestionType': '문제 유형 선택',
    'languageKnowledgeVocabulary': '언어지식 · 문자·어휘',
    'languageKnowledgeGrammar': '언어지식 · 문법',
    'readingComprehension': '독해',
    'listeningComprehension': '청해',
    'sectionListening': '청해',
    'listeningQuizInstruction': '대화를 듣고 가장 알맞은 답을 고르세요.',
    'playAudio': '음성 재생',
    'askAiTutor': 'AI 튜터에게 질문',
    'askingAiTutor': 'AI 튜터에게 묻는 중…',
    'aiTutor': 'AI 튜터',
    'aiGeneratedNotice': 'AI가 생성한 안내에는 오류가 있을 수 있습니다.',
    'whyCorrect': '이 답이 정답인 이유',
    'whyWrong': '선택한 답이 틀린 이유',
    'keyEvidence': '핵심 근거',
    'learningPoints': '핵심 학습 포인트',
    'explainChoices': '선택지 설명',
    'showEvidence': '핵심 근거 보기',
    'giveExample': '비슷한 예문 보기',
    'aiTutorUnavailable': '현재 AI 튜터를 사용할 수 없습니다. 기존 해설은 계속 확인할 수 있습니다.',
    'aiTutorBusy':
        'AI 튜터가 일시적인 요청 한도에 도달했습니다. 1분 정도 기다린 후 다시 시도해 주세요. 기존 해설은 계속 확인할 수 있습니다.',
    'tryAgain': '다시 시도',
    'wasHelpful': '도움이 되었나요?',
    'thanksFeedback': '의견을 보내 주셔서 감사합니다.',
    'askFollowUp': '추가 질문하기',
    'typeYourQuestion': '질문을 입력하세요…',
    'sendMessage': '보내기',
    'temporaryChatNotice': '이 대화는 창을 닫으면 삭제됩니다.',
    'aiReplyError': 'AI 튜터가 답변하지 못했습니다. 다시 시도해 주세요.',
    'conversationLimit': '이번 대화의 질문 한도에 도달했습니다.',
    'unlockDaysTitle': 'Day {day} 잠금 해제',
    'unlockDaysBody': '짧은 광고를 시청하면 Day {day} 학습을 시작할 수 있습니다.',
    'finishPreviousDaysTitle': '이전 학습일을 먼저 완료해 주세요',
    'finishPreviousDaysBody': '이 학습일을 시작하려면 Day 1~{day} 학습을 완료해야 합니다.',
    'watchAd': '광고 시청',
    'hideWord': '단어 숨기기',
    'showWord': '단어 보기',
    'hideMeanings': '뜻 숨기기',
    'showMeanings': '뜻 보기',
    'covered': '가려짐',
    'on': '켜짐',
    'off': '꺼짐',
    'groupLanguage': '언어',
    'groupReadingAudio': '읽기 및 발음',
    'groupReview': '복습',
    'groupDisplay': '화면',
    'autoReview': '자동 복습',
    'autoReviewHint':
        '카드마다 단어, 뜻, 읽기를 선택한 순서대로 하나씩 보여 주고 다음 카드로 자동으로 넘어갑니다. 이미 학습을 마친 날에만 작동합니다.',
    'autoReviewEnable': '자동 복습 사용',
    'autoReviewOrder': '공개 순서',
    'autoReviewSpeed': '단계별 시간',
    'autoReviewSecondsFormat': '{n}초',
    'elementWord': '단어',
    'elementMeanings': '뜻',
    'elementReading': '읽기',
    'pauseAutoReview': '일시정지',
    'resumeAutoReview': '재생',
    'recallCover': '가리고 떠올리기',
    'recallCoverHint':
        '단어와 뜻을 테이프로 가리고 기억나는 대로 말해 보세요. 학습 화면 아래 버튼으로 바로 켜고 끌 수 있습니다.',
    'coverWordBody': '단어를 가립니다. 예문 속 같은 단어도 함께 가려집니다.',
    'coverMeaningsTitle': '뜻',
    'coverMeaningsBody': '뜻 숨기기가 가리는 범위를 고르세요.',
    'coverMeaningAndTranslation': '뜻 + 번역',
    'coverMeaningAndTranslationBody': '뜻과 예문 번역을 모두 가립니다.',
    'coverMeaningOnly': '뜻만',
    'coverMeaningOnlyBody': '뜻을 가리고, 예문 번역 속 해당 뜻도 함께 가립니다.',
    'coverTranslationOnly': '번역만',
    'coverTranslationOnlyBody': '예문 번역만 가립니다.',
    'ttsVolume': '발음 볼륨',
    'ttsVolumeHint': '발음 재생 볼륨을 어디에서 가져올지 선택하세요.',
    'volumeSystem': '시스템 볼륨',
    'volumeSystemBody': '기기의 미디어 볼륨을 그대로 따릅니다. 볼륨 버튼으로 조절하세요.',
    'volumeSlider': '직접 설정',
    'volumeSliderBody': '기기 볼륨과 관계없이 아래 크기로 재생하고, 재생이 끝나면 기기 볼륨을 되돌립니다.',
    'volumeCurrentSystem': '현재 시스템 볼륨',
    'volumeLevel': '볼륨',
    'eyeComfortSubtitle': '학습하는 동안 따뜻한 색조 적용',
  };

  String call(String key) =>
      (languageCode == 'ko' ? _ko : _en)[key] ?? _en[key] ?? key;
}

extension AppStringsContext on BuildContext {
  AppStrings get strings =>
      AppStrings(Localizations.localeOf(this).languageCode);
}
